### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by RGlanville**

### CODE REVIEW

**Review by lauren-vault — APPROVED** [review]
Looks good 🤷🏼‍♀️

**Comment by eifr-vault** [comment]
YES

**Comment by eifr-vault** [comment]
try to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) if there's no linked ticket (for better clarity)

**Comment by RGlanville** [comment]
> try to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) if there's no linked ticket (for better clarity)

Sorry linked ticket manually in shortcut but yes I should have done this.

**Comment by RGlanville** [comment]
[sc-28679]

**Pull request merged**
